---
id: Socket_Client
name: Socket_Client
full: Network socket client library
description: A library that provides an abstract PHP network socket client.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
  optional:
    ext:
      openssl: '*'
autoload:
  classmap:
    - lib/
